### ISSUE TITLE
Need a small Demo.

### ISSUE THREAD

**Issue by harielakanti** [WirecardMobileServices/Wirecard-ePOS-iOS#1]
Can you please show some small example, how we can give the inputs like cardDetails, CVV, endDate etc along with OTP Screen for iOS App(Swift or ObjectiveC)

**Comment by RadoslavDanko** [comment]
Hi,  the ePOS SDK purpose is to obtain the Card data by using the mPOS terminal.
It is not possible to enter the card data manually. 
If you are after eCOM solution please have a look at our other product https://github.com/wirecard/paymentSDK-iOS
