### ISSUE TITLE
NSLocalizedString not working after init of WDePOS

### ISSUE THREAD

**Issue by schwindt** [WirecardMobileServices/Wirecard-ePOS-iOS#2]
After I init the SDK with 

WDePOS *sdk = [WDePOS sharedInstance];

the default methods:
NSLocalizedString(@"key")
[NSBundle.mainBundle localizedStringForKey:(@"key") value:@"" table:nil];

are not working anymore...

**Comment by WirecardMobileServices** [comment]
Hi,
We will look into it asap. In the mean time, could you please tell us what SDK version are you using, and if you recall a previous version without it?

**Comment by schwindt** [comment]
2.10.0 not working
2.9.2 not working
2.9.1 not working
**2.9.0 not working
2.8.0 working**
2.7.0 working
2.5.0 working

I guess it's because of your WDLocalizationManager and the new method:
NSString* _Nonnull WDLocalizedString(NSString * _Nonnull key);

**Comment by WirecardMobileServices** [comment]
Hotfix 2.10.1 released including fix for localizations, please let me know the result.

**Comment by schwindt** [comment]
looks much better now. fixed my translation problem.
